services:
  keycloak:
    image: quay.io/keycloak/keycloak:26.2.0
    ports:
      - 8080:8080
    env_file: .env
    command: start-dev
  gitea:
    image: gitea/gitea:1.23.7
    ports:
      - 3000:3000
      - 222:22
    network_mode: "host"
    volumes:
      - ./gitea:/data
volumes:
  gitea:
